[package]
name = "shulker-crds"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "crdgen"
path = "src/bin/crdgen.rs"
doc = false
test = false
# required-features = ["crdgen-bin"]

[lib]
name = "shulker_crds"
path = "src/lib.rs"

[features]
default = []
# crdgen-bin = ["serde_yaml"]

[dependencies]
google-agones-crds.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
shulker-utils.workspace = true
strum.workspace = true

[build-dependencies]
base64.workspace = true
