[package]
name = "shulker-crds"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "crdgen"
path = "src/crdgen.rs"
doc = false
test = false

[lib]
name = "shulker_crds"
path = "src/lib.rs"

[features]
default = []

[dependencies]
k8s-openapi.workspace = true
kube.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
shulker-utils = { path = "../shulker-utils" }

[build-dependencies]
base64.workspace = true
