apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shulker-system

resources:
  - ../../resources/crd
  - ../../resources/components/shulker-operator
  - ../../resources/components/shulker-addon-matchmaking

images:
  - name: ghcr.io/jeremylvln/shulker-operator
    newTag: next
  - name: ghcr.io/jeremylvln/shulker-addon-matchmaking
    newTag: next
