[package]
name = "shulker-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
testing = []

[dependencies]
chrono.workspace = true
