[package]
name = "shulker-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "shulker_utils"
path = "src/lib.rs"

[features]
default = []
testing = []

[dependencies]
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
