name: Install Tools & Dependencies
description: Install required tools and dependencies

inputs:
  install-rust:
    description: "Whether to install Rust"
    required: true
    default: "true"
  install-java:
    description: "Whether to install Java"
    required: true
    default: "true"
  node-version:
    description: "The Node.js version to use"
    required: true
    default: "22"
  rust-version:
    description: "The Rust version to use"
    required: true
    default: "stable"
  java-version:
    description: "The Java version to use"
    required: true
    default: "21"

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Use Rust ${{ inputs.rust-version }}
      if: ${{ inputs.install-rust == 'true' }}
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ inputs.rust-version }}
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Use Java ${{ inputs.java-version }}
      if: ${{ inputs.install-java == 'true' }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ inputs.java-version }}
        cache: "gradle"

    - name: Prepare sccache-cache
      if: ${{ inputs.install-rust == 'true' }}
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Install Node.js dependencies
      shell: bash
      run: pnpm install
