[package]
name = "shulker-kube-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "shulker_kube_utils"
path = "src/lib.rs"

[features]
default = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
hostname.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
shulker-utils.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
shulker-utils = { workspace = true, features = ["testing"] }

[lints]
workspace = true
