complexity:
  TooManyFunctions:
    active: false

naming:
  MemberNameEqualsClassName:
    excludes:
      - "**/kubernetes/models/**"

style:
  MaxLineLength:
    active: false
  ForbiddenVoid:
    ignoreOverridden: true
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    active: false
