apiVersion: v1
kind: Service
metadata:
  name: shulker-operator-metrics
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: shulker-operator-metrics
    app.kubernetes.io/component: shulker-operator
    app.kubernetes.io/part-of: shulker
spec:
  selector:
    app.kubernetes.io/name: shulker-operator
    app.kubernetes.io/instance: shulker-operator
    app.kubernetes.io/component: shulker-operator
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
