apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: shulker-system
  labels:
    control-plane: shulker-operator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/created-by: shulker
    app.kubernetes.io/part-of: shulker
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: shulker-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
      labels:
        control-plane: shulker-operator
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        ports:
        - name: metrics-proxy
          containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
      - name: operator
        image: ghcr.io/jeremylvln/shulker-operator
        imagePullPolicy: Always
        command:
        - /shulker-operator
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        ports:
        - containerPort: 8080
          protocol: TCP
          name: metrics
        - containerPort: 8081
          protocol: TCP
          name: health
        - containerPort: 9090
          protocol: TCP
          name: api
        - containerPort: 9443
          protocol: TCP
          name: webhooks
        volumeMounts:
        - mountPath: /tmp/serving-certs
          name: cert
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
      volumes:
      - name: cert
        secret:
          secretName: webhook-server-cert
          defaultMode: 420
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    # - arm64
                    # - ppc64le
                    # - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
