apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: shulker-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: operator-api-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: shulker
    app.kubernetes.io/part-of: shulker
    app.kubernetes.io/managed-by: kustomize
  name: operator-api-service
  namespace: shulker-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: api
  selector:
    control-plane: shulker-operator
