apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: with-custom-configuration
  replicas: 1
  template:
    spec:
      clusterRef:
        name: with-custom-configuration
      tags:
        - lobby
      version:
        channel: Paper
        name: "1.21.1"
      config:
        world:
          url: https://example.com/my-world.tar.gz
        plugins:
          - urlFrom:
              mavenRef:
                repositoryUrl: https://example.com/maven
                groupId: com.example
                artifactId: myplugin
                version: "1.0.0"
                credentialsSecretName: example-repo-secret
        patches:
          - url: https://example.com/add-config-to-myplugin.tar.gz
          - url: https://example.com/add-something-after.tar.gz
          - url: https://example.com/remove-everything-at-the-end.tar.gz
        maxPlayers: 100
