apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shulker-addon-matchmaking-workload
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: shulker-addon-matchmaking-workload
    app.kubernetes.io/component: shulker-addon-matchmaking-rbac
    app.kubernetes.io/part-of: shulker
rules:
  - apiGroups:
      - matchmaking.shulkermc.io
    resources:
      - matchmakingqueues
    verbs: [get, list, watch]
  - apiGroups:
      - matchmaking.shulkermc.io
    resources:
      - matchmakingqueues
      - matchmakingqueues/status
    verbs: [update, patch]

  - apiGroups:
      - ''
    resources:
      - events
    verbs: [create]

  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs: [list]
