//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) Jérémy Levilain
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchmakingProfile) DeepCopyInto(out *MatchmakingProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.MatchmakingProfileTemplate.DeepCopyInto(&out.MatchmakingProfileTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchmakingProfile.
func (in *MatchmakingProfile) DeepCopy() *MatchmakingProfile {
	if in == nil {
		return nil
	}
	out := new(MatchmakingProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MatchmakingProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchmakingProfileList) DeepCopyInto(out *MatchmakingProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MatchmakingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchmakingProfileList.
func (in *MatchmakingProfileList) DeepCopy() *MatchmakingProfileList {
	if in == nil {
		return nil
	}
	out := new(MatchmakingProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MatchmakingProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchmakingProfileSpec) DeepCopyInto(out *MatchmakingProfileSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchmakingProfileSpec.
func (in *MatchmakingProfileSpec) DeepCopy() *MatchmakingProfileSpec {
	if in == nil {
		return nil
	}
	out := new(MatchmakingProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchmakingProfileTemplate) DeepCopyInto(out *MatchmakingProfileTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchmakingProfileTemplate.
func (in *MatchmakingProfileTemplate) DeepCopy() *MatchmakingProfileTemplate {
	if in == nil {
		return nil
	}
	out := new(MatchmakingProfileTemplate)
	in.DeepCopyInto(out)
	return out
}
