apiVersion: apps/v1
kind: Deployment
metadata:
  name: shulker-addon-matchmaking-director
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: shulker-addon-matchmaking-director
    app.kubernetes.io/component: shulker-addon-matchmaking
    app.kubernetes.io/part-of: shulker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shulker-addon-matchmaking-director
      app.kubernetes.io/instance: shulker-addon-matchmaking-director
      app.kubernetes.io/component: shulker-addon-matchmaking
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shulker-addon-matchmaking-director
        app.kubernetes.io/instance: shulker-addon-matchmaking-director
        app.kubernetes.io/component: shulker-addon-matchmaking
    spec:
      containers:
        - name: shulker-addon-matchmaking-director
          image: ghcr.io/jeremylvln/shulker-addon-matchmaking
          imagePullPolicy: Always
          args:
            - --metrics-bind-address=0.0.0.0:8080
          env:
            - name: OPEN_MATCH_BACKEND_HOST
              value: open-match-backend.open-match
            - name: OPEN_MATCH_BACKEND_GRPC_PORT
              value: '50505'
            - name: SHULKER_API_HOST
              value: 'shulker-operator.shulker-system'
            - name: SHULKER_API_GRPC_PORT
              value: '8080'
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - 'ALL'
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: shulker-addon-matchmaking
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
