{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shulker-operator.serviceAccountName" . }}
  labels:
    {{- include "shulker-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-operator-rbac
    {{- with .Values.operator.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}