apiVersion: v1
kind: Service
metadata:
  name: {{ template "shulker-operator.fullname" . }}
  labels:
    {{- include "shulker-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-operator
  {{- with .Values.operator.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.operator.service.type }}
  ports:
    - name: api-grpc
      port: 9090
      protocol: TCP
      targetPort: api-grpc
  selector:
    {{- include "shulker-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-operator
