[build]
target-dir = "dist/rust"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# [target.'cfg(all())']
# rustflags = [
#   "-Wunused_crate_dependencies",
# ]
