apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - serviceaccounts
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agones.dev
  resources:
  - fleets
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters
  - minecraftclusters/status
  - minecraftserverfleets
  - minecraftserverfleets/status
  - minecraftservers
  - minecraftservers/status
  - proxyfleets
  - proxyfleets/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
