apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: mounting-volumes
  replicas: 1
  template:
    spec:
      clusterRef:
        name: mounting-volumes
      tags:
        - lobby
      version:
        channel: Paper
        name: "1.21.1"
      config: {}
      podOverrides:
        volumeMounts:
          - name: extra-volume
            mountPath: /mnt/extra-volume
        volumes:
          - name: extra-volume
            emptyDir: {}
