/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.shulkermc.models.V1alpha1MinecraftServerSpecPodOverridesEnv;
import io.shulkermc.models.V1alpha1MinecraftServerSpecPodOverridesLivenessProbe;
import io.shulkermc.models.V1alpha1MinecraftServerSpecPodOverridesReadinessProbe;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Overrides configuration for the Minecraft Server pod.
 */
@ApiModel(description = "Overrides configuration for the Minecraft Server pod.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T15:48:00.143Z[Etc/UTC]")
public class V1alpha1MinecraftServerSpecPodOverrides {
  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private List<V1alpha1MinecraftServerSpecPodOverridesEnv> env = null;

  public static final String SERIALIZED_NAME_LIVENESS_PROBE = "livenessProbe";
  @SerializedName(SERIALIZED_NAME_LIVENESS_PROBE)
  private V1alpha1MinecraftServerSpecPodOverridesLivenessProbe livenessProbe;

  public static final String SERIALIZED_NAME_READINESS_PROBE = "readinessProbe";
  @SerializedName(SERIALIZED_NAME_READINESS_PROBE)
  private V1alpha1MinecraftServerSpecPodOverridesReadinessProbe readinessProbe;

  public static final String SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS = "terminationGracePeriodSeconds";
  @SerializedName(SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS)
  private Long terminationGracePeriodSeconds;


  public V1alpha1MinecraftServerSpecPodOverrides env(List<V1alpha1MinecraftServerSpecPodOverridesEnv> env) {
    
    this.env = env;
    return this;
  }

  public V1alpha1MinecraftServerSpecPodOverrides addEnvItem(V1alpha1MinecraftServerSpecPodOverridesEnv envItem) {
    if (this.env == null) {
      this.env = new ArrayList<>();
    }
    this.env.add(envItem);
    return this;
  }

   /**
   * Additional environment variables to add to the Minecraft Server.
   * @return env
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional environment variables to add to the Minecraft Server.")

  public List<V1alpha1MinecraftServerSpecPodOverridesEnv> getEnv() {
    return env;
  }


  public void setEnv(List<V1alpha1MinecraftServerSpecPodOverridesEnv> env) {
    this.env = env;
  }


  public V1alpha1MinecraftServerSpecPodOverrides livenessProbe(V1alpha1MinecraftServerSpecPodOverridesLivenessProbe livenessProbe) {
    
    this.livenessProbe = livenessProbe;
    return this;
  }

   /**
   * Get livenessProbe
   * @return livenessProbe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1MinecraftServerSpecPodOverridesLivenessProbe getLivenessProbe() {
    return livenessProbe;
  }


  public void setLivenessProbe(V1alpha1MinecraftServerSpecPodOverridesLivenessProbe livenessProbe) {
    this.livenessProbe = livenessProbe;
  }


  public V1alpha1MinecraftServerSpecPodOverrides readinessProbe(V1alpha1MinecraftServerSpecPodOverridesReadinessProbe readinessProbe) {
    
    this.readinessProbe = readinessProbe;
    return this;
  }

   /**
   * Get readinessProbe
   * @return readinessProbe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1MinecraftServerSpecPodOverridesReadinessProbe getReadinessProbe() {
    return readinessProbe;
  }


  public void setReadinessProbe(V1alpha1MinecraftServerSpecPodOverridesReadinessProbe readinessProbe) {
    this.readinessProbe = readinessProbe;
  }


  public V1alpha1MinecraftServerSpecPodOverrides terminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
    return this;
  }

   /**
   * Number of seconds before force killing the pod after a graceful termination request. Defaults to 1 minute.
   * @return terminationGracePeriodSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of seconds before force killing the pod after a graceful termination request. Defaults to 1 minute.")

  public Long getTerminationGracePeriodSeconds() {
    return terminationGracePeriodSeconds;
  }


  public void setTerminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftServerSpecPodOverrides v1alpha1MinecraftServerSpecPodOverrides = (V1alpha1MinecraftServerSpecPodOverrides) o;
    return Objects.equals(this.env, v1alpha1MinecraftServerSpecPodOverrides.env) &&
        Objects.equals(this.livenessProbe, v1alpha1MinecraftServerSpecPodOverrides.livenessProbe) &&
        Objects.equals(this.readinessProbe, v1alpha1MinecraftServerSpecPodOverrides.readinessProbe) &&
        Objects.equals(this.terminationGracePeriodSeconds, v1alpha1MinecraftServerSpecPodOverrides.terminationGracePeriodSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(env, livenessProbe, readinessProbe, terminationGracePeriodSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftServerSpecPodOverrides {\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    livenessProbe: ").append(toIndentedString(livenessProbe)).append("\n");
    sb.append("    readinessProbe: ").append(toIndentedString(readinessProbe)).append("\n");
    sb.append("    terminationGracePeriodSeconds: ").append(toIndentedString(terminationGracePeriodSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

