/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.shulkermc.models.V1alpha1MinecraftClusterStatusConditions;
import io.shulkermc.models.V1alpha1MinecraftClusterStatusServerPool;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MinecraftClusterStatus defines the observed state of MinecraftCluster
 */
@ApiModel(description = "MinecraftClusterStatus defines the observed state of MinecraftCluster")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T15:49:50.494Z[Etc/UTC]")
public class V1alpha1MinecraftClusterStatus {
  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1MinecraftClusterStatusConditions> conditions = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROXIES = "proxies";
  @SerializedName(SERIALIZED_NAME_PROXIES)
  private Integer proxies;

  public static final String SERIALIZED_NAME_SERVER_POOL = "serverPool";
  @SerializedName(SERIALIZED_NAME_SERVER_POOL)
  private List<V1alpha1MinecraftClusterStatusServerPool> serverPool = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVERS = "servers";
  @SerializedName(SERIALIZED_NAME_SERVERS)
  private Integer servers;


  public V1alpha1MinecraftClusterStatus conditions(List<V1alpha1MinecraftClusterStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1MinecraftClusterStatus addConditionsItem(V1alpha1MinecraftClusterStatusConditions conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions represent the latest available observations of a MinecraftCluster object.
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "Conditions represent the latest available observations of a MinecraftCluster object.")

  public List<V1alpha1MinecraftClusterStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1MinecraftClusterStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1MinecraftClusterStatus proxies(Integer proxies) {
    
    this.proxies = proxies;
    return this;
  }

   /**
   * Number of proxies.
   * @return proxies
  **/
  @ApiModelProperty(required = true, value = "Number of proxies.")

  public Integer getProxies() {
    return proxies;
  }


  public void setProxies(Integer proxies) {
    this.proxies = proxies;
  }


  public V1alpha1MinecraftClusterStatus serverPool(List<V1alpha1MinecraftClusterStatusServerPool> serverPool) {
    
    this.serverPool = serverPool;
    return this;
  }

  public V1alpha1MinecraftClusterStatus addServerPoolItem(V1alpha1MinecraftClusterStatusServerPool serverPoolItem) {
    this.serverPool.add(serverPoolItem);
    return this;
  }

   /**
   * Pool of Minecraft Servers linked to this Minecraft Cluster.
   * @return serverPool
  **/
  @ApiModelProperty(required = true, value = "Pool of Minecraft Servers linked to this Minecraft Cluster.")

  public List<V1alpha1MinecraftClusterStatusServerPool> getServerPool() {
    return serverPool;
  }


  public void setServerPool(List<V1alpha1MinecraftClusterStatusServerPool> serverPool) {
    this.serverPool = serverPool;
  }


  public V1alpha1MinecraftClusterStatus servers(Integer servers) {
    
    this.servers = servers;
    return this;
  }

   /**
   * Number of servers inside the server pool.
   * @return servers
  **/
  @ApiModelProperty(required = true, value = "Number of servers inside the server pool.")

  public Integer getServers() {
    return servers;
  }


  public void setServers(Integer servers) {
    this.servers = servers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftClusterStatus v1alpha1MinecraftClusterStatus = (V1alpha1MinecraftClusterStatus) o;
    return Objects.equals(this.conditions, v1alpha1MinecraftClusterStatus.conditions) &&
        Objects.equals(this.proxies, v1alpha1MinecraftClusterStatus.proxies) &&
        Objects.equals(this.serverPool, v1alpha1MinecraftClusterStatus.serverPool) &&
        Objects.equals(this.servers, v1alpha1MinecraftClusterStatus.servers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, proxies, serverPool, servers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftClusterStatus {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    proxies: ").append(toIndentedString(proxies)).append("\n");
    sb.append("    serverPool: ").append(toIndentedString(serverPool)).append("\n");
    sb.append("    servers: ").append(toIndentedString(servers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

