/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Defines the defired state of a MinecraftCluster. Most, to not say all, fields configurable in a Minecraft Cluster can be configured in this CRD.
 */
@ApiModel(description = "Defines the defired state of a MinecraftCluster. Most, to not say all, fields configurable in a Minecraft Cluster can be configured in this CRD.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-11T15:16:21.509Z[Etc/UTC]")
public class V1alpha1MinecraftClusterSpec {
  public static final String SERIALIZED_NAME_MAVEN_SECRET_NAME = "mavenSecretName";
  @SerializedName(SERIALIZED_NAME_MAVEN_SECRET_NAME)
  private String mavenSecretName;


  public V1alpha1MinecraftClusterSpec mavenSecretName(String mavenSecretName) {
    
    this.mavenSecretName = mavenSecretName;
    return this;
  }

   /**
   * Name of the Kubernetes Secret contaning the Maven secret to use. It must contains a &#x60;username&#x60; and &#x60;password&#x60; fields.
   * @return mavenSecretName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the Kubernetes Secret contaning the Maven secret to use. It must contains a `username` and `password` fields.")

  public String getMavenSecretName() {
    return mavenSecretName;
  }


  public void setMavenSecretName(String mavenSecretName) {
    this.mavenSecretName = mavenSecretName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftClusterSpec v1alpha1MinecraftClusterSpec = (V1alpha1MinecraftClusterSpec) o;
    return Objects.equals(this.mavenSecretName, v1alpha1MinecraftClusterSpec.mavenSecretName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mavenSecretName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftClusterSpec {\n");
    sb.append("    mavenSecretName: ").append(toIndentedString(mavenSecretName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

