/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Version the Minecraft Server has to run.
 */
@ApiModel(description = "Version the Minecraft Server has to run.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T15:48:00.143Z[Etc/UTC]")
public class V1alpha1MinecraftServerSpecVersion {
  /**
   * Channel of the version to use. Defaults to Vanilla meaning that the server will run Mojang&#39;s official dedicated server.
   */
  @JsonAdapter(ChannelEnum.Adapter.class)
  public enum ChannelEnum {
    VANILLA("Vanilla"),
    
    FORGE("Forge"),
    
    FABRIC("Fabric"),
    
    SPIGOT("Spigot"),
    
    PAPER("Paper"),
    
    AIRPLANE("Airplane"),
    
    PUFFERFISH("Pufferfish"),
    
    PURPUR("Purpur"),
    
    MAGMA("Magma"),
    
    MOHIST("Mohist"),
    
    CATSERVER("Catserver"),
    
    CANYON("Canyon"),
    
    SPONGEVANILLA("SpongeVanilla"),
    
    LIMBO("Limbo"),
    
    CRUCIBLE("Crucible");

    private String value;

    ChannelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChannelEnum fromValue(String value) {
      for (ChannelEnum b : ChannelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ChannelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChannelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChannelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ChannelEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private ChannelEnum channel;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1alpha1MinecraftServerSpecVersion channel(ChannelEnum channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * Channel of the version to use. Defaults to Vanilla meaning that the server will run Mojang&#39;s official dedicated server.
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Channel of the version to use. Defaults to Vanilla meaning that the server will run Mojang's official dedicated server.")

  public ChannelEnum getChannel() {
    return channel;
  }


  public void setChannel(ChannelEnum channel) {
    this.channel = channel;
  }


  public V1alpha1MinecraftServerSpecVersion name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the version to use.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the version to use.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftServerSpecVersion v1alpha1MinecraftServerSpecVersion = (V1alpha1MinecraftServerSpecVersion) o;
    return Objects.equals(this.channel, v1alpha1MinecraftServerSpecVersion.channel) &&
        Objects.equals(this.name, v1alpha1MinecraftServerSpecVersion.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftServerSpecVersion {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

