/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.shulkermc.models.V1alpha1MinecraftServerStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MinecraftServerStatus defines the observed state of MinecraftServer
 */
@ApiModel(description = "MinecraftServerStatus defines the observed state of MinecraftServer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-11T15:13:51.331Z[Etc/UTC]")
public class V1alpha1MinecraftServerStatus {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1MinecraftServerStatusConditions> conditions = new ArrayList<>();


  public V1alpha1MinecraftServerStatus address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Address of the Minecraft Server pod.
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Address of the Minecraft Server pod.")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public V1alpha1MinecraftServerStatus conditions(List<V1alpha1MinecraftServerStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1MinecraftServerStatus addConditionsItem(V1alpha1MinecraftServerStatusConditions conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions represent the latest available observations of a MinecraftServer object.
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "Conditions represent the latest available observations of a MinecraftServer object.")

  public List<V1alpha1MinecraftServerStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1MinecraftServerStatusConditions> conditions) {
    this.conditions = conditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftServerStatus v1alpha1MinecraftServerStatus = (V1alpha1MinecraftServerStatus) o;
    return Objects.equals(this.address, v1alpha1MinecraftServerStatus.address) &&
        Objects.equals(this.conditions, v1alpha1MinecraftServerStatus.conditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, conditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftServerStatus {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

