/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * URL to a downloadable world archive.
 */
@ApiModel(description = "URL to a downloadable world archive.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T15:48:00.143Z[Etc/UTC]")
public class V1alpha1MinecraftServerSpecWorld {
  public static final String SERIALIZED_NAME_DISABLE_END = "disableEnd";
  @SerializedName(SERIALIZED_NAME_DISABLE_END)
  private Boolean disableEnd;

  public static final String SERIALIZED_NAME_DISABLE_NETHER = "disableNether";
  @SerializedName(SERIALIZED_NAME_DISABLE_NETHER)
  private Boolean disableNether;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public V1alpha1MinecraftServerSpecWorld disableEnd(Boolean disableEnd) {
    
    this.disableEnd = disableEnd;
    return this;
  }

   /**
   * Whether to allow the Minecraft Server to generate a End world and the players to enter it.
   * @return disableEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to allow the Minecraft Server to generate a End world and the players to enter it.")

  public Boolean getDisableEnd() {
    return disableEnd;
  }


  public void setDisableEnd(Boolean disableEnd) {
    this.disableEnd = disableEnd;
  }


  public V1alpha1MinecraftServerSpecWorld disableNether(Boolean disableNether) {
    
    this.disableNether = disableNether;
    return this;
  }

   /**
   * Whether to allow the Minecraft Server to generate a Nether world and the players to enter it.
   * @return disableNether
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to allow the Minecraft Server to generate a Nether world and the players to enter it.")

  public Boolean getDisableNether() {
    return disableNether;
  }


  public void setDisableNether(Boolean disableNether) {
    this.disableNether = disableNether;
  }


  public V1alpha1MinecraftServerSpecWorld url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL to a downloable world.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to a downloable world.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MinecraftServerSpecWorld v1alpha1MinecraftServerSpecWorld = (V1alpha1MinecraftServerSpecWorld) o;
    return Objects.equals(this.disableEnd, v1alpha1MinecraftServerSpecWorld.disableEnd) &&
        Objects.equals(this.disableNether, v1alpha1MinecraftServerSpecWorld.disableNether) &&
        Objects.equals(this.url, v1alpha1MinecraftServerSpecWorld.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disableEnd, disableNether, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MinecraftServerSpecWorld {\n");
    sb.append("    disableEnd: ").append(toIndentedString(disableEnd)).append("\n");
    sb.append("    disableNether: ").append(toIndentedString(disableNether)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

