/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.shulkermc.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.shulkermc.models.V1alpha1ProxyDeploymentStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProxyDeploymentStatus defines the observed state of ProxyDeployment
 */
@ApiModel(description = "ProxyDeploymentStatus defines the observed state of ProxyDeployment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T15:48:55.272Z[Etc/UTC]")
public class V1alpha1ProxyDeploymentStatus {
  public static final String SERIALIZED_NAME_AVAILABLE_REPLICAS = "availableReplicas";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_REPLICAS)
  private Integer availableReplicas;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1ProxyDeploymentStatusConditions> conditions = new ArrayList<>();

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;


  public V1alpha1ProxyDeploymentStatus availableReplicas(Integer availableReplicas) {
    
    this.availableReplicas = availableReplicas;
    return this;
  }

   /**
   * Number of available replicas in Proxy Deployment.
   * @return availableReplicas
  **/
  @ApiModelProperty(required = true, value = "Number of available replicas in Proxy Deployment.")

  public Integer getAvailableReplicas() {
    return availableReplicas;
  }


  public void setAvailableReplicas(Integer availableReplicas) {
    this.availableReplicas = availableReplicas;
  }


  public V1alpha1ProxyDeploymentStatus conditions(List<V1alpha1ProxyDeploymentStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1ProxyDeploymentStatus addConditionsItem(V1alpha1ProxyDeploymentStatusConditions conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions represent the latest available observations of a ProxyDeployment object.
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "Conditions represent the latest available observations of a ProxyDeployment object.")

  public List<V1alpha1ProxyDeploymentStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1ProxyDeploymentStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1ProxyDeploymentStatus replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Number of total replicas in Proxy Deployment.
   * @return replicas
  **/
  @ApiModelProperty(required = true, value = "Number of total replicas in Proxy Deployment.")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ProxyDeploymentStatus v1alpha1ProxyDeploymentStatus = (V1alpha1ProxyDeploymentStatus) o;
    return Objects.equals(this.availableReplicas, v1alpha1ProxyDeploymentStatus.availableReplicas) &&
        Objects.equals(this.conditions, v1alpha1ProxyDeploymentStatus.conditions) &&
        Objects.equals(this.replicas, v1alpha1ProxyDeploymentStatus.replicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableReplicas, conditions, replicas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ProxyDeploymentStatus {\n");
    sb.append("    availableReplicas: ").append(toIndentedString(availableReplicas)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

