{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "shulker-addon-matchmaking.fullname" . }}:leader-election
  labels:
    {{- include "shulker-addon-matchmaking.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-addon-matchmaking-rbac
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - shulker-addon-matchmaking.shulkermc.io
    verbs: ["get", "update", "patch"]
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "shulker-addon-matchmaking.fullname" . }}:leader-election
  labels:
    {{- include "shulker-addon-matchmaking.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-addon-matchmaking-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "shulker-addon-matchmaking.fullname" . }}:leader-election
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "shulker-addon-matchmaking.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
