{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shulker-addon-matchmaking.serviceAccountName" . }}
  labels:
    {{- include "shulker-addon-matchmaking.labels" . | nindent 4 }}
    app.kubernetes.io/component: shulker-addon-matchmaking-rbac
    {{- with .Values.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}